# ProSpect configuration parameters.
# For more information see ProSpect documentation: https://github.com/asgr/ProSpect

# SF-Z history
#-------------
# Fixed parameters associated with each function may be added and removed.

massfunc: massfunc_exp    # ProSpect mass function. massfun_(b5, const, dtau, exp, exp_burst,
                          # p2, p3, p3_burst, p4, p6, snorm, snorm_trunc, snorm_burst, snorm_burst_trunc)
                          
Z: Zfunc_massmap_lin    # ProSpect metallicity function. Zfunc_(p2, massmap_lin, massmap_box)

# Cosmology
#----------
z: 0.1    # Cosmological redshift of the source

H0: 67.8    # Hubble constant as defined at z=0. [km/s/Mpc]
OmegaM: 0.308    # Omega Matter today.
OmegaL: 0.692    # Omega Lambda today
ref: NULL    # The reference cosmology to use. (137, 737, Planck13, Planck15, Planck18, WMAP9, WMAP7, WMAP5, WMAP3, WMAP1, Millennium, GiggleZ)
unimax: 1.38e+10    # Maximum allowed age of any stellar population relative to z=0. [yr]
agemax: NULL    # Maximum allowed age of any stellar population relative to the redshift of the observed galaxy. [yr]
LumDist_Mpc: NULL    # Luminosity distance at given redshift [cm]

# SPS
#----
speclib: BC03lr    # Spectral library to use. (BC03lr, BC03hr, EMILES)
sparse: 5    # Amount of space sampling of the spectra to make.

# Dust
#-----
Dale: Dale_NormTot    # Dale dust library to use. Dale_(interp, Msol, NormAGN, NormSFR, NormTot, Orig)
Dale_M2L_func: NULL    # Function to convert alpha_SF to mass-to-light. Dale_(M2L, M2L_func, MsolM2L)
tau_birth: 1    # Optical depth of birth cloud dust.
tau_screen: 0.3    # Same as above, but for dust screen.
tau_AGN: 1    # Save as above, but for AGN.
pow_birth: -0.7    # Power to further raise dust attenuation of birth clouds.
pow_screen: -0.7    # Same as above, but for dust screen.
pow_AGN: -0.7    # Same as above, but for AGN.
alpha_SF_birth: 1    # Alpha slope of the birth cloud dust.
alpha_SF_AGN: 0    # Same as above but for dust screen.
alpha_SF_screen: 3    # Same as above but for AGN.

# AGN
#----
AGN: NULL    # The AGN template to use. AGN_(UnOb, UnOb_Sparse)
AGNlum: 0    # AGN bolemetric luminosity [erg/s]
AGNct: 60    # Opening angle of torus [deg]
AGNal: 4    # Gamma dust parameter.
AGNbe: -0.5    # Beta dust parameter.
AGNta: 1    # Optical depth.
AGNrm: 60     # Outer to inner torus radius ratio.
AGNan: 30    # Angle of observation in, where 0 is edge on with torus, and 90 is polar aligned. [deg]

# Radio
#------
addradio_SF: FALSE    # Include free-free and synchrotron radio continuum associated with star formation?
Te_SF: 10000    # Effective HII nebular plasma temperature used for the SF component. [K]
ff_frac_SF: 0.1    # Free-free HII nebular plasma thermal radio emission contribution fraction at 1.4 GHz associated with SF.
ff_power_SF: -0.1    # Power-law slope of the free-free nebular plasma thermal radio emission associated with SF.
sy_power_SF: -0.8    # Power-law slope of the synchrotron radio emission associated with SF.

addradio_AGN: FALSE    # Include free-free and synchrotron radio continuum associated with AGN?
Te_AGN: 10000    # Effective HII nebular plasma temperature used for the AGN component. [K]
ff_frac_AGN: 0.1    # Free-free HII nebular plasma thermal radio emission contribution fraction at 1.4 GHz associated with AGN.
ff_power_AGN: -0.1    # Power-law slope of the free-free nebular plasma thermal radio emission associated with AGN.
sy_power_AGN: -0.8    # Power-law slope of the synchrotron radio emission associated with AGN.

# IGM
#----
Eb: 0    # Additional attenuation at the 2175.8 Ang dust bump.
L0: 2175.8    # Location of the 2175.8 Ang dust bump. [A]
LFWHM: 470    # Width of the 2175.8 Ang dust bump. [A]
IGMabsorb: 0    # Absorbing fraction for the intervening IGM. #TODO: Define some functions for this.

# Other
#------
like: norm    # The type of likelihood. (norm, st, chisq)
optim_iters: 2    # Number of CMA/LD loops.
Niters: [100, 100]    # Number of iterations per CMA/LD.
NfinalMCMC: 100    # Number of iterations in the final MCMC run.
pz_resolution: 101    # Number of gridpoints for binning the posterior.

verbose: FALSE    # Should verbose messages be shown?

# Free parameters
#----------------
# Format: ("parmaeter_name": [lower_limit, upper_limit])
fit:
  z: [-3, 1]
  mSFR: [-4, 3]
  mpeak: [-2, 1]
  mperiod: [-1, 1]
  mskew: [-0.5, 1]
  tau_birth: [-2.5, 1.5]
  tau_screen: [-2.5, 1]

  logged: [TRUE, TRUE, TRUE, TRUE, FALSE, TRUE, TRUE]    # Should each parameter be fit in log space?


